package projectSI.persistence.entities;

// Generated 26.11.2015 21:36:01 by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PubAutori generated by hbm2java
 */
@Entity
@Table(name = "pub_autori", catalog = "unistatsdb")
public class PubAutori implements java.io.Serializable {

	private static final long serialVersionUID = 3923948947833416913L;
	
	private Integer id;
	private Person person;
	private BigDecimal podiel;
	private PubPublikacie publikacia;

	public PubAutori() {
	}

	public PubAutori(Person person, BigDecimal podiel, PubPublikacie publikacia) {
		this.person = person;
		this.podiel = podiel;
		this.publikacia = publikacia;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "ldap_id")
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Column(name = "podiel", precision = 10)
	public BigDecimal getPodiel() {
		return this.podiel;
	}

	public void setPodiel(BigDecimal podiel) {
		this.podiel = podiel;
	}

	@ManyToOne
	@JoinColumn(name="id_publikacia")
	public PubPublikacie getPublikacia() {
		return publikacia;
	}

	public void setPublikacia(PubPublikacie publikacia) {
		this.publikacia = publikacia;
	}

}
