package projectSI.persistence.entities;

// Generated 26.11.2015 21:36:01 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PubEpcKodyUkazovatele generated by hbm2java
 */
@Entity
@Table(name = "pub_epc_kody_ukazovatele", catalog = "unistatsdb")
public class PubEpcKodyUkazovatele implements java.io.Serializable {

	private static final long serialVersionUID = -6066909606870304264L;
	
	private Integer id;
	private String kod;
	private int ukazovatel;

	public PubEpcKodyUkazovatele() {
	}

	public PubEpcKodyUkazovatele(String kod, int ukazovatel) {
		this.kod = kod;
		this.ukazovatel = ukazovatel;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "kod", nullable = false, length = 3)
	public String getKod() {
		return this.kod;
	}

	public void setKod(String kod) {
		this.kod = kod;
	}

	@Column(name = "ukazovatel", nullable = false)
	public int getUkazovatel() {
		return this.ukazovatel;
	}

	public void setUkazovatel(int ukazovatel) {
		this.ukazovatel = ukazovatel;
	}

}
