package projectSI.persistence.entities;

// Generated 26.11.2015 21:36:01 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * PubEpcSkupinyId generated by hbm2java
 */
@Entity
@Table(name = "pub_epc_skupiny", catalog = "unistatsdb")
@NamedQueries({
	@NamedQuery(name="Skupina.findAll", query="SELECT DISTINCT s FROM PubEpcSkupiny s")
})
public class PubEpcSkupiny implements java.io.Serializable {
	
	private static final long serialVersionUID = -6651321408485256276L;
	
	private String idSkupiny;
	private String popisSkupiny;

	public PubEpcSkupiny() {
	}

	public PubEpcSkupiny(String idSkupiny, String popisSkupiny) {
		this.idSkupiny = idSkupiny;
		this.popisSkupiny = popisSkupiny;
	}

	@Id
	@Column(name = "ID_skupiny", nullable = false, length = 3)
	public String getIdSkupiny() {
		return this.idSkupiny;
	}

	public void setIdSkupiny(String idSkupiny) {
		this.idSkupiny = idSkupiny;
	}

	@Column(name = "popis_skupiny", nullable = false)
	public String getPopisSkupiny() {
		return this.popisSkupiny;
	}

	public void setPopisSkupiny(String popisSkupiny) {
		this.popisSkupiny = popisSkupiny;
	}
}
