package projectSI.persistence.entities;

// Generated 26.11.2015 21:36:01 by Hibernate Tools 4.3.1

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PubEpcKody generated by hbm2java
 */
@Entity
@Table(name = "pub_epc_kody", catalog = "unistatsdb")
public class PubEpcKody implements java.io.Serializable {

	private static final long serialVersionUID = -1334853569880878220L;
	
	private Integer id;
	private String kod;
	private String popisKategorie;
	private PubEpcSkupiny skupina;
	private int zohladnenaVRozpocte;
	private int ukazovatel;
	
	private List<PubPublikacie> publikacieList;

	public PubEpcKody() {
	}

	public PubEpcKody(String kod, String popisKategorie, PubEpcSkupiny skupina,
			int zohladnenaVRozpocte, int ukazovatel) {
		this.kod = kod;
		this.popisKategorie = popisKategorie;
		this.skupina = skupina;
		this.zohladnenaVRozpocte = zohladnenaVRozpocte;
		this.ukazovatel = ukazovatel;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "kod", nullable = false, length = 3)
	public String getKod() {
		return this.kod;
	}

	public void setKod(String kod) {
		this.kod = kod;
	}

	@Column(name = "popis_kategorie", nullable = false)
	public String getPopisKategorie() {
		return this.popisKategorie;
	}

	public void setPopisKategorie(String popisKategorie) {
		this.popisKategorie = popisKategorie;
	}

	@ManyToOne
	@JoinColumn(name = "ID_skupiny", nullable = false)
	public PubEpcSkupiny getSkupina() {
		return this.skupina;
	}

	public void setSkupina(PubEpcSkupiny skupina) {
		this.skupina = skupina;
	}

	@Column(name = "zohladnena_v_rozpocte", nullable = false)
	public int getZohladnenaVRozpocte() {
		return this.zohladnenaVRozpocte;
	}

	public void setZohladnenaVRozpocte(int zohladnenaVRozpocte) {
		this.zohladnenaVRozpocte = zohladnenaVRozpocte;
	}

	@Column(name = "ukazovatel", nullable = false)
	public int getUkazovatel() {
		return this.ukazovatel;
	}

	public void setUkazovatel(int ukazovatel) {
		this.ukazovatel = ukazovatel;
	}

	@OneToMany(mappedBy="epcKod")
	public List<PubPublikacie> getPublikacieList() {
		return publikacieList;
	}

	public void setPublikacieList(List<PubPublikacie> publikacieList) {
		this.publikacieList = publikacieList;
	}

}
