package projectSI.persistence.entities;

// Generated 26.11.2015 21:36:01 by Hibernate Tools 4.3.1

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.ws.rs.ext.ParamConverter.Lazy;

/**
 * PubPublikacie generated by hbm2java
 */
@Entity
@Table(name = "pub_publikacie", catalog = "unistatsdb")
public class PubPublikacie implements java.io.Serializable {

	private static final long serialVersionUID = -4536772102986776127L;
	
	private Integer id;
	private PubEpcKody epcKod;
	private String identifikaciaOrgId;
	private int rokVykazovania;
	private int rokVydania;
	private String nazovHlavny;
	private String podnazov;
	private String autorskeZahlavie;
	private String zoznamAutorov;
	private String typ;
	private int idCasopis;
	private String vydavatel;
	private int vydanie;
	private int stran;
	private String oznacenieZvazku;
	private String isbn;
	private String citacnyZaznam;
	private String doi;
	private String woS;
	private String scopus;
	
	private List<PubAutori> pubAutoriList;

	public PubPublikacie() {
	}

	public PubPublikacie(PubEpcKody epcKod, String identifikaciaOrgId,
			int rokVykazovania, int rokVydania, String nazovHlavny,
			String podnazov, String autorskeZahlavie, String zoznamAutorov,
			String typ, int idCasopis, String vydavatel, int vydanie,
			int stran, String oznacenieZvazku, String isbn,
			String citacnyZaznam, String doi, String woS, String scopus) {
		this.epcKod = epcKod;
		this.identifikaciaOrgId = identifikaciaOrgId;
		this.rokVykazovania = rokVykazovania;
		this.rokVydania = rokVydania;
		this.nazovHlavny = nazovHlavny;
		this.podnazov = podnazov;
		this.autorskeZahlavie = autorskeZahlavie;
		this.zoznamAutorov = zoznamAutorov;
		this.typ = typ;
		this.idCasopis = idCasopis;
		this.vydavatel = vydavatel;
		this.vydanie = vydanie;
		this.stran = stran;
		this.oznacenieZvazku = oznacenieZvazku;
		this.isbn = isbn;
		this.citacnyZaznam = citacnyZaznam;
		this.doi = doi;
		this.woS = woS;
		this.scopus = scopus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Warning: foreign key does not exist in table kodyEpc (0, maybe other values)
	 * @return
	 */
	@ManyToOne (fetch = FetchType.LAZY)	
	@JoinColumn(name = "ID_kod_EPC", nullable = false)
	public PubEpcKody getEpcKod() {
		return this.epcKod;
	}

	public void setEpcKod(PubEpcKody epcKod) {
		this.epcKod = epcKod;
	}

	@Column(name = "identifikacia_orgID", nullable = false)
	public String getIdentifikaciaOrgId() {
		return this.identifikaciaOrgId;
	}

	public void setIdentifikaciaOrgId(String identifikaciaOrgId) {
		this.identifikaciaOrgId = identifikaciaOrgId;
	}

	@Column(name = "rok_vykazovania", nullable = false)
	public int getRokVykazovania() {
		return this.rokVykazovania;
	}

	public void setRokVykazovania(int rokVykazovania) {
		this.rokVykazovania = rokVykazovania;
	}

	@Column(name = "rok_vydania", nullable = false)
	public int getRokVydania() {
		return this.rokVydania;
	}

	public void setRokVydania(int rokVydania) {
		this.rokVydania = rokVydania;
	}

	@Column(name = "nazov_hlavny", nullable = false)
	public String getNazovHlavny() {
		return this.nazovHlavny;
	}

	public void setNazovHlavny(String nazovHlavny) {
		this.nazovHlavny = nazovHlavny;
	}

	@Column(name = "podnazov", nullable = false)
	public String getPodnazov() {
		return this.podnazov;
	}

	public void setPodnazov(String podnazov) {
		this.podnazov = podnazov;
	}

	@Column(name = "autorske_zahlavie", nullable = false, length = 65535)
	public String getAutorskeZahlavie() {
		return this.autorskeZahlavie;
	}

	public void setAutorskeZahlavie(String autorskeZahlavie) {
		this.autorskeZahlavie = autorskeZahlavie;
	}

	@Column(name = "zoznam_autorov", nullable = false, length = 65535)
	public String getZoznamAutorov() {
		return this.zoznamAutorov;
	}

	public void setZoznamAutorov(String zoznamAutorov) {
		this.zoznamAutorov = zoznamAutorov;
	}

	@Column(name = "typ", nullable = false, length = 65535)
	public String getTyp() {
		return this.typ;
	}

	public void setTyp(String typ) {
		this.typ = typ;
	}

	@Column(name = "ID_casopis", nullable = false)
	public int getIdCasopis() {
		return this.idCasopis;
	}

	public void setIdCasopis(int idCasopis) {
		this.idCasopis = idCasopis;
	}

	@Column(name = "vydavatel", nullable = false)
	public String getVydavatel() {
		return this.vydavatel;
	}

	public void setVydavatel(String vydavatel) {
		this.vydavatel = vydavatel;
	}

	@Column(name = "vydanie", nullable = false)
	public int getVydanie() {
		return this.vydanie;
	}

	public void setVydanie(int vydanie) {
		this.vydanie = vydanie;
	}

	@Column(name = "stran", nullable = false)
	public int getStran() {
		return this.stran;
	}

	public void setStran(int stran) {
		this.stran = stran;
	}

	@Column(name = "oznacenie_zvazku", nullable = false, length = 65535)
	public String getOznacenieZvazku() {
		return this.oznacenieZvazku;
	}

	public void setOznacenieZvazku(String oznacenieZvazku) {
		this.oznacenieZvazku = oznacenieZvazku;
	}

	@Column(name = "ISBN", nullable = false, length = 25)
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Column(name = "citacny_zaznam", nullable = false, length = 65535)
	public String getCitacnyZaznam() {
		return this.citacnyZaznam;
	}

	public void setCitacnyZaznam(String citacnyZaznam) {
		this.citacnyZaznam = citacnyZaznam;
	}

	@Column(name = "DOI", nullable = false)
	public String getDoi() {
		return this.doi;
	}

	public void setDoi(String doi) {
		this.doi = doi;
	}

	@Column(name = "WoS", nullable = false, length = 2)
	public String getWoS() {
		return this.woS;
	}

	public void setWoS(String woS) {
		this.woS = woS;
	}

	@Column(name = "scopus", nullable = false, length = 2)
	public String getScopus() {
		return this.scopus;
	}

	public void setScopus(String scopus) {
		this.scopus = scopus;
	}

	@OneToMany(mappedBy="publikacia")
	public List<PubAutori> getPubAutoriList() {
		return pubAutoriList;
	}

	public void setPubAutoriList(List<PubAutori> pubAutoriList) {
		this.pubAutoriList = pubAutoriList;
	}

}
